# Generated by Django 4.2.7 on 2023-11-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_celular_tablet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tablet',
        ),
    ]
