# Generated by Django 4.2.7 on 2023-11-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auto',
            new_name='Monitor',
        ),
    ]
