# Generated by Django 4.2.7 on 2023-11-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_rename_auto_monitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='fecha_creacion',
            new_name='fecha_de_creacion',
        ),
    ]
