# Generated by Django 4.2.7 on 2023-11-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosextra',
            old_name='User',
            new_name='user',
        ),
    ]
