# Generated by Django 4.2.7 on 2023-11-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account1', '0003_datosextra_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosextra',
            old_name='biografia',
            new_name='descripcion',
        ),
    ]
